### ISSUE TITLE
Question about HNSW index creation

### ISSUE THREAD

**Issue by danielfleischer** [qdrant/qdrant-haystack#9]
The workflow of a dense document store is creating all the points with `write_documents` and then creating their embeddings with `update_embeddings`.

My question is about the HNSW graph; `write_documents` creates points with random vectors (fill_missing_embeddings=True). So the HNSW graph is built around these random points. Later when using the real embeddings, does the graph adapts to the real vectors? Does doing this 2 step process lead to suboptimal searching results and it might be better to have the embeddings prepared for a single insertion via `write_documents`?  Thanks~

**Comment by kacperlukawski** [comment]
@danielfleischer it would definitely be better to have the embeddings prepared beforehand. We implemented the possibility to store data without the embeddings, so it is compatible with the other engines. However, the HNSW graph will be rebuilt when you store new embeddings, so no need to worry. Of course, you'll be building the graph twice, so that's overhead.

**Comment by danielfleischer** [comment]
Thanks!
